### ISSUE TITLE
Manager mode bugs

### ISSUE THREAD

**Issue by Dandielo** [Dandielo/DtlCitizensTrader#69]
Please send me here all weird things you noticed in manager mode, any item slot changes, disappearing, duplications etc etc

**Comment by KaleFaolan** [comment]
I have noticed the following:
- Items disappearing between adding them to shop inventory and going into pricing mode
- Items used to price items in shop inventory will randomly disappear
- Items disappearing in mid-move from player inventory to shop inventory
- While pricing items, it will suddenly switch from pricing to where you add/take items in
- Sometimes taking an item out of trader inventory won't actually take it out. It takes multiple tries
- Don't know if it's related or not: two of my traders are forgetting their stock. One forgets all enchanted books and the other is forgetting chainmail. Again, not sure if it's caused by this or another bug, but I'll be happy to open another issue for this if you think that the manager mode isn't the issue
- (More to come, possibly and my pleasure)

**Comment by Dandielo** [comment]
Thanks a lot

**Comment by Catorii** [comment]
I noticed two of the things KaleFaolan did, as well. The bug we reported a while back (the "breaks traders completely" bug) is probably caused by this manager mode bug, would be my guess. The issues we have are:

-Items in trader inventory disappearing or moving (and their prices bugging) when moving between stock mode and pricing mode. Removing the bugged block doesn't seem to fix the issue most of the time, so we usually have to start a whole new NPC and delete the old one. With our server, if we implement an NPC with this bugged block, its price will constantly reset to $0 and it may disappear or replace other non-bugged blocks.

-This just started more recently (as in probably just a few weeks ago), but we've noticed the NPCs will twitch just a little bit every 10-20 seconds. They all do it at the same time, it's barely noticeable, but unfortunately, if you are in manager mode in their pricing tab when this happens, they'll kick you out of pricing every time they do this and take you back to stock...thus resetting any prices you just did. We're having to resort to setting one price at a time and swapping to stock to save the price we just did.

**Comment by Dandielo** [comment]
hmm... so many bugs just to allow ppl to make tiered item sets :D 

first issues is somehow connected with the InventoryClickEvent, what I've noticed from my dev tests, on random clicks (With items in hand/mouse pointer) bukkit/MC sends 4 additional Click Events, that messes up my system. This happens because those events sends two clicks with slots -999 witch is equal to (Throw out item) and as because I need to prevent any dupes I'm handling these requests in some otherway. But, because 2 of those four clicks are the slot some1 clicked, it reads them as "set the item here", or "remove the item". 

So -999 makes items disappear and they should be visible on stock change on the first empty slot, all others are messing up Manager Modes, 

That second issue you are telling me about does it happens only to traders? Or does it happens to really each NPC?

**Comment by KaleFaolan** [comment]
I can confirm the "twitch" happens to all NPCs. It's kinda like...they move up slightly and then go back into position....like a person when they get up on their tiptoes. Watched with a trader and a regular NPC do it.

**Comment by Dandielo** [comment]
lol this really is getting more weird with each bug Oo atm I'm thinking of do my traders does such a mess or has Bukkit Team made some awesome bugs, or did NPC's got their own thoughts ?

**Comment by Catorii** [comment]
Yeah, happens both to traders and normal NPCs with us, too. It's very odd, but it is pretty recent. I'm not sure exactly when it started, since we stopped working on new NPCs for a while with the bugs we were having, but it may have been something from the latest version? Not sure.

**Comment by KaleFaolan** [comment]
New issues, again not sure it's related or not:
- I have one trader that's not displaying the price for just one item. That's it, out of all the other traders that are behaving and out of all the other items, just one isn't displaying the right price. It still sells the item at the right price, but doesn't display it when you hover over it. I also went into the config file and manually fixed the price in there....and it reverted back to displaying nothing. May poke the config file again today. _Gets out his poking stick_

**Comment by Catorii** [comment]
A bug we encountered this past week is related to the blocks glitching or going missing, I think:

We don't use stack prices, but for some reason on one of our NPCs, the prices changed to Stack Price on 4 different stacks of items (only two actual items, torches and ladders, but each had a full stack and a half stack in the NPC). Going into manger mode and changing it manually back to the normal pricing scheme worked for a few minutes...until we reloaded Citizens (as would happen after a server restart), and the stacks bugged again.

Have not seen other NPCs do this, but I figured it was worth mentioning, as this is a new bug for us.

**Comment by Dandielo** [comment]
Is there a possibility to check all your bugs in game? It's much more obvious for me when I can see that bug, on the actual NPC.

**Comment by sajro94** [comment]
I encountered a bug today that whenever I attempt to acces the buy tab it says that I do not have permissions for that, but I am an OP and I even have these permissions aswell:
    - dtl.trader.options.manage
    - dtl.trader.options.sell-amounts
    - dtl.trader.options.buy
    - dtl.trader.options.sell
    - dtl.trader.*
    - dtl.*
When I try to acces the sell tab it say ''Entered stock managing''
