### ISSUE TITLE
Integration with Denizen scripts?

### ISSUE THREAD

**Issue by CressAlbane2** [Dandielo/DtlCitizensTrader#70]
This is apparently compatible with Denizen scripts, but I wasn't able to find much information about that.  Looking at the source code it seems there are a few Denizen commands, - TRADER, - TRANSACTION, and - TRADERCREATE, but there seems to be very little documentation about how these are used.  Also, it appears that a Denizen who has a scripted behavior on click doesn't open the trade window.
Does one of these commands open the trade window during interaction?  Is there documentation on how to use these commands anywhere?  Are these commands complete?
Looking at the source code for the - TRADER command, it actually seems that none of the arguments are accounted for except opening a new trader.  Is this the case?

**Comment by Dandielo** [comment]
No documentation because i couldn't find the time to finish this feature. Now it's quite impossible after making all these changes to v2.5 to add more features. 

So far TRADER counts only as opening the trader window, you may just type - TRADER and it opens the window.

To disallow r.click opening the window, you need to enable the Trader Trigger (it will from up now trigger this trigger and a On Trader action, when right clicked)

TRANSACTION atm works only for "buying from trader" + there are some <tags> you may use. If i will finish all bug fixes I will first finish limits and after this I will finish this feature. If you want and know a bit coding you may always send pull requests :)

**Comment by CressAlbane2** [comment]
Thank you very much for the quick reply.  The information about the trader trigger was what I needed.

**Comment by Dandielo** [comment]
You are always welcome :)
